### ISSUE TITLE
Android 使用后图片显示,ios还是不行

### ISSUE THREAD

**Issue by feige-2011** [smallnew/react-native-smartassets#2]
SmartAssets.setiOSRelateMainBundlePath('./ios/platform.ios.bundle');
SmartAssets.setiOSRelateMainBundlePath('./ios/index.ios.bundle');
试了这两种写法,都不行,大神指点一下奥

**Comment by smallnew** [comment]
不加 ./  ，而且assets目录需要跟bundle同级

**Comment by feige-2011** [comment]
<img width="530" alt="屏幕快照 2019-04-02 上午9 39 25" src="https://user-images.githubusercontent.com/19235739/55369944-3d2fac80-552b-11e9-8e73-801b6e31d391.png">
SmartAssets.setiOSRelateMainBundlePath('ios/platform.ios.bundle');
SmartAssets.setiOSRelateMainBundlePath('ios/index.ios.bundle');
SmartAssets.setiOSRelateMainBundlePath('platform.ios.bundle');
SmartAssets.setiOSRelateMainBundlePath('index.ios.bundle');
您好! 我照上面的路径做了尝试
bundle 文件是和 assets 路径一致的,试了这几种方法都没有显示图片,
Bundle路径是要写业务包的路径,还是基础包的路径? 另外 Bundle 包的名字有影响么,必须要写成 main.bundle么?
我看到在您提供的例子里是没有加 SmartAssets.setiOSRelateMainBundlePath('xxxxxx')这一句的,但是图面是正常显示的,望大神指点?

**Comment by feige-2011** [comment]
如果 ios 必须提供 bundle包路径, 那我从网上下载到沙盒的 bundle包是不是就不能使用这种打包方案?

**Comment by smallnew** [comment]
这个项目的意思是：你把bundle下载到了沙盒，这个时候如果还想要用iOS mainBundle（ipa）里面的资源可以用这个。setiOSRelateMainBundlePath就是让你找到iOS mainBundle（ipa）里面的资源的位置，如果有不清楚的可以在源码中打log看下资源路径拼接逻辑，打log还是很方便的

**Comment by feige-2011** [comment]
谢谢啦,我这边找到问题了,是我忘了把打包生成的资源文件添加到原生项目里了
